---
- name: Uninstall K3s from Control Plane Node 01
  hosts: master_1,master_2
  become: yes
  tasks:
    - name: Uninstall K3s from control plane node 01
      shell: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: true

- name: Uninstall K3s from Worker Nodes
  hosts: worker
  become: yes
  tasks:
    - name: Uninstall K3s from worker nodes
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: true
